"use strict";
const test = require("node:test");
const assert = require("node:assert/strict");
const { createSandbox, setup, completePhase1, knockoutFixture, clickAction, plain, STATE_KEY, SUMMARY_KEY, OPERATOR_KEY } = require("./harness");
const { HEADERS, ACTIONS, handFixture } = require("./oracles");

const field = (s, role, id) => s.document.querySelector('[data-role="' + role + '"][data-match-id="' + id + '"]');
test("operator-page: searchable team pickers commit by click/keyboard and preserve unrelated drafts", async () => {
    const s = createSandbox({ page: "admin" });
    setup(s, 50, 20, { phase1MatchesPerTeam: 3, qualifiedCount: 16 });
    s.A.generatePhase1();
    const m = s.state().phase1.matches[0];
    const other = s.state().phase1.matches[1];
    const target = s.state().teams.find((team) => team.id !== m.homeTeamId && team.id !== m.awayTeamId);
    let input = field(s, "phase1-home-team", m.id);
    assert.equal(input.tagName, "INPUT");
    assert.equal(input.value, s.R.getTeamNameById(s.state(), m.homeTeamId));
    assert.equal(input.getAttribute("aria-expanded"), "false");
    assert.equal(input.closest(".team-picker").querySelector('[role="listbox"]').hidden, true);
    assert.equal(s.document.querySelector(".match-search-label"), null);
    field(s, "phase1-home", other.id).value = "13";
    field(s, "phase1-away", other.id).value = "7";
    field(s, "phase1-home", m.id).value = "99";
    await input.focus();
    assert.equal(input.closest(".team-picker").querySelectorAll('[role="option"]').length, 49);
    const committed = m.homeTeamId;
    input.value = target.name.toLowerCase();
    await input.dispatch("input");
    assert.equal(m.homeTeamId, committed);
    assert.equal(input.closest(".team-picker").querySelectorAll('[role="option"]').length, 1);
    await input.dispatch("keydown", { key: "Enter" });
    assert.equal(m.homeTeamId, target.id);
    assert.equal(m.status, "scheduled");
    assert.equal(m.homeGoals, null);
    assert.equal(field(s, "phase1-home", m.id).value, "");
    assert.equal(field(s, "phase1-home", other.id).value, "13");
    assert.equal(field(s, "phase1-away", other.id).value, "7");
    input = field(s, "phase1-home-team", m.id);
    assert.equal(input.getAttribute("aria-expanded"), "false");
    assert.equal(s.document.activeElement, input);
    const writes = s.storage.writes.length;
    await input.focus();
    input.value = "NoSuchTeam";
    await input.dispatch("input");
    assert.match(input.closest(".team-picker").textContent, /No matching teams/);
    await input.dispatch("keydown", { key: "Enter" });
    assert.equal(s.storage.writes.length, writes);
    await input.dispatch("keydown", { key: "Escape" });
    assert.equal(input.value, target.name);
    await input.focus();
    input.value = "";
    await input.dispatch("input");
    assert.equal(m.homeTeamId, target.id);
    await input.dispatch("keydown", { key: "ArrowDown" });
    const list = input.closest(".team-picker");
    const first = list.querySelector('[role="option"]');
    assert.equal(input.getAttribute("aria-activedescendant"), first.id);
    await input.dispatch("keydown", { key: "ArrowUp" });
    const last = list.querySelectorAll('[role="option"]').at(-1);
    assert.equal(input.getAttribute("aria-activedescendant"), last.id);
    await last.click();
    assert.equal(m.homeTeamId, last.getAttribute("data-team-id"));
    assert.equal(s.alerts.length, 0);
    input = field(s, "phase1-home-team", m.id);
    await input.focus(); input.value = "unfinished";
    await input.dispatch("focusout");
    assert.equal(input.value, input.getAttribute("data-team-name"));
    const reloaded = createSandbox({ page: "admin", initial: { [STATE_KEY]: s.S.exportState() } });
    assert.equal(field(reloaded, "phase1-home-team", m.id).getAttribute("data-team-id"), m.homeTeamId);
});

test("operator-page: knockout picker changes teams without scoring and typed labels never become IDs", async () => {
    const s = knockoutFixture({ page: "admin", count: 8 });
    const m = s.state().knockout.rounds[0].matches[0];
    const target = s.state().teams.find((team) => team.id !== m.homeTeamId && team.id !== m.awayTeamId);
    let input = field(s, "ko-away-team", m.id);
    await input.focus();
    input.value = target.name;
    await input.dispatch("input");
    await input.closest(".team-picker").querySelector('[role="option"]').click();
    assert.equal(m.awayTeamId, target.id);
    assert.equal(m.status, "scheduled");
    input = field(s, "ko-away-team", m.id);
    input.value = "arbitrary text";
    field(s, "ko-home", m.id).value = "2";
    field(s, "ko-away", m.id).value = "0";
    await clickAction(s, "ko-save", { "data-match-id": m.id });
    assert.equal(m.awayTeamId, target.id);
    assert.equal(m.status, "completed");
    input = field(s, "ko-away-team", m.id);
    assert.equal(input.disabled, true);
    await input.dispatch("input");
    assert.equal(input.getAttribute("aria-expanded"), "false");
    await clickAction(s, "ko-reopen", { "data-match-id": m.id });
    input = field(s, "ko-away-team", m.id);
    await input.focus(); input.value = target.name;
    await input.dispatch("input");
    const before = s.S.exportState();
    await input.dispatch("keydown", { key: "Enter" });
    assert.equal(s.S.exportState(), before, "same team must not mutate the reopened match");
    const duplicate = s.state().teams.find((team) => team.id !== m.homeTeamId && team.id !== m.awayTeamId);
    s.S.update((state) => {
        state.teams.find((team) => team.id === m.awayTeamId).name = "Shared <name>";
        state.teams.find((team) => team.id === duplicate.id).name = "Shared <name>";
    });
    input = field(s, "ko-away-team", m.id);
    await input.focus(); input.value = "shared";
    await input.dispatch("input");
    assert.equal(input.closest(".team-picker").querySelectorAll('[role="option"]').length, 2);
    const oldTeamId = m.awayTeamId;
    await input.dispatch("keydown", { key: "Enter" });
    assert.equal(m.awayTeamId, oldTeamId, "ambiguous text must not select a team");
    const option = input.closest(".team-picker").querySelectorAll('[role="option"]')
        .find((item) => item.getAttribute("data-team-id") === duplicate.id);
    assert.equal(option.textContent, "Shared <name>");
    await option.click();
    assert.equal(m.awayTeamId, duplicate.id);
});

async function saveOnPage(s, match, knockout = false) {
    const prefix = knockout ? "ko" : "phase1";
    field(s, prefix + "-home", match.id).value = "2";
    field(s, prefix + "-away", match.id).value = "0";
    await clickAction(s, prefix + "-save", { "data-match-id": match.id });
    assert.equal(match.status, "completed");
}
test("operator-page: empty/malformed boot, one 1000ms interval, subscription rerender", () => {
    for (const initial of [{}, { [STATE_KEY]: "{" }]) {
        const s = createSandbox({ page: "admin", initial });
        assert.equal(s.state().teams.length, 0);
        assert.match(s.el("teams-list").innerHTML, /No teams yet/);
        assert.deepEqual([...s.timers.values()].map((timer) => [timer.kind, timer.delay]), [["interval", 1000]]);
        assert.equal(s.el("btn-start-knockout").disabled, true);
        s.A.addTeam("Subscription team");
        assert.match(s.el("teams-list").innerHTML, /Subscription team/);
        assert.equal(s.el("section-setup").open, true);
        s.advance(1000); s.runTimers(1000);
        assert.equal(s.storage.writes.filter(([key]) => key === STATE_KEY).length, 1);
    }
});
test("operator-page: forms, config minutes conversion and validation alerts", async () => {
    const s = createSandbox({ page: "admin" }); setup(s, 4, 2);
    s.el("team-name").value = "  Form \t Team ";
    await s.el("form-add-team").dispatch("submit");
    assert.equal(s.state().teams.at(-1).name, "Form Team"); assert.equal(s.el("team-name").value, "");
    s.el("terrain-name").value = "Form Field";
    await s.el("form-add-terrain").dispatch("submit");
    assert.equal(s.state().terrains.at(-1).name, "Form Field");
    s.el("cfg-match-duration").value = "7"; s.el("cfg-pause-duration").value = "2";
    s.el("cfg-seeding").value = "random"; s.el("cfg-third-place").checked = true;
    await s.el("form-config").dispatch("submit");
    assert.equal(s.state().config.matchDurationSeconds, 420);
    assert.equal(s.state().config.pauseDurationSeconds, 120);
    assert.equal(s.state().config.seedingPolicy, "random"); assert.equal(s.state().config.thirdPlaceMatch, true);
    s.el("cfg-match-duration").value = "x";
    await s.el("form-config").dispatch("submit");
    assert.equal(s.alerts.at(-1), "Match duration must be >= 1 second");
    s.el("team-name").value = "form team"; await s.el("form-add-team").dispatch("submit");
    assert.equal(s.alerts.at(-1), "Team name already exists");
    s.el("terrain-name").value = ""; await s.el("form-add-terrain").dispatch("submit");
    assert.equal(s.alerts.at(-1), "Terrain name is required");
    s.A.resetAll();
    await s.el("btn-generate-phase1").click();
    assert.equal(s.alerts.at(-1), "Need at least 2 teams");
    await s.el("btn-start-knockout").click();
    assert.equal(s.alerts.at(-1), "Generate phase 1 first");
});
test("operator-page: every emitted data-action handled, page scoring and stage gates", async () => {
    const s = createSandbox({ page: "admin", now: 1000 });
    const seen = new Set();
    const emitted = new Set();
    const collect = () => s.document.querySelectorAll("[data-action]").forEach((el) => emitted.add(el.getAttribute("data-action")));
    const click = async (action, attrs) => { collect(); seen.add(action); await clickAction(s, action, attrs); collect(); };
    setup(s, 4, 2, { thirdPlaceMatch: true });
    await click("team-remove", { "data-team-id": "t4" });
    s.A.addTeam("Team 04");
    await click("terrain-remove", { "data-terrain-id": "f2" }); s.A.addTerrain("Field 2");
    await click("scroll-top");
    await click("progress-jump", { "data-target-section": "setup" });
    await s.el("section-setup").querySelector(":scope > summary").click();
    await s.el("btn-expand-all").click(); await s.el("btn-collapse-all").click();
    assert.equal(s.el("section-setup").open, false);
    await s.el("btn-generate-phase1").click();
    assert.equal(s.el("team-name").disabled, true);
    assert.equal(s.el("btn-generate-phase1").disabled, true);
    assert.equal(s.el("btn-start-knockout").disabled, true);
    const first = s.state().phase1.matches[0];
    await click("round-toggle", { "data-round-key": "phase1:0" });
    await click("progress-jump", { "data-target-section": "phase1" });
    await click("phase1-start-round", { "data-round-key": "0" });
    s.advance(10000);
    await click("phase1-pause-round", { "data-round-key": "0" });
    s.advance(5000);
    await click("phase1-resume-round", { "data-round-key": "0" });
    await click("match-pause", { "data-match-id": first.id });
    s.advance(2000);
    await click("match-resume", { "data-match-id": first.id });
    field(s, "phase1-home", first.id).value = "3"; field(s, "phase1-away", first.id).value = "0";
    await click("phase1-save", { "data-match-id": first.id });
    assert.equal(first.homeGoals, 3);
    assert.equal(field(s, "phase1-home", first.id).disabled, true);
    await click("phase1-reopen", { "data-match-id": first.id });
    assert.equal(field(s, "phase1-home", first.id).disabled, false);
    await click("phase1-save", { "data-match-id": first.id });
    await click("phase1-stop-round", { "data-round-key": "0" });
    completePhase1(s);
    assert.equal(s.el("btn-start-knockout").disabled, false);
    await s.el("btn-start-knockout").click();
    assert.equal(s.el("btn-start-knockout").disabled, true); assert.equal(s.el("btn-back-to-phase1").disabled, false);
    await click("progress-jump", { "data-target-section": "knockout" });
    const round = s.state().knockout.rounds[0];
    await click("ko-start-round", { "data-round-key": round.id });
    await click("ko-pause-round", { "data-round-key": round.id });
    s.advance(1000);
    await click("ko-resume-round", { "data-round-key": round.id });
    for (const match of round.matches) {
        field(s, "ko-home", match.id).value = "2"; field(s, "ko-away", match.id).value = "0";
        await click("ko-save", { "data-match-id": match.id });
    }
    const final = s.state().knockout.rounds[1].matches[0];
    assert.equal(field(s, "ko-home-team", final.id), null, "Later round has static participants");
    field(s, "ko-home", final.id).value = "2"; field(s, "ko-away", final.id).value = "0";
    await click("ko-save", { "data-match-id": final.id });
    assert.ok(s.state().knockout.championTeamId);
    await click("ko-reopen", { "data-match-id": final.id });
    assert.equal(s.state().knockout.championTeamId, null);
    await click("ko-stop-round", { "data-round-key": round.id });
    await click("team-remove", { "data-team-id": s.state().teams[0].id });
    assert.equal(s.alerts.at(-1), "Cannot edit teams or terrains after phase 1 is generated. Reset state to restart.");
    assert.deepEqual([...emitted].sort(), [...ACTIONS].sort());
    assert.deepEqual([...seen].sort(), [...ACTIONS].sort());
});
test("operator-page: escaping hostile names and completed/scheduled control locks", async () => {
    const s = createSandbox({ page: "admin" }); setup(s);
    s.A.addTeam('<script>"A"&\'</script>'); s.A.removeTeam("t4");
    assert.match(s.el("teams-list").innerHTML, /&lt;script&gt;&quot;A&quot;&amp;&#39;&lt;\/script&gt;/);
    assert.doesNotMatch(s.el("teams-list").innerHTML, /<script>/);
    s.A.generatePhase1();
    const m = s.state().phase1.matches[0];
    const hostile = s.state().teams.find((team) => team.name.startsWith("<script>"));
    const hostilePicker = field(s, m.homeTeamId === hostile.id ? "phase1-home-team" : "phase1-away-team", m.id);
    await hostilePicker.focus();
    assert.match(hostilePicker.closest(".team-picker").querySelector('[role="listbox"]').innerHTML,
        /&lt;script&gt;&quot;A&quot;&amp;&#39;&lt;\/script&gt;/);
    assert.equal(hostilePicker.closest(".team-picker").querySelector("script"), null);
    assert.equal(field(s, "phase1-home", m.id).disabled, false);
    assert.equal(field(s, "phase1-home-team", m.id).disabled, false);
    const reopen = s.document.querySelector('[data-action="phase1-reopen"][data-match-id="' + m.id + '"]');
    assert.equal(reopen.disabled, true);
    await field(s, "phase1-home-team", m.id).focus();
    const options = field(s, "phase1-home-team", m.id).closest(".team-picker").querySelectorAll('[role="option"]');
    assert.ok(!options.some((option) => option.getAttribute("data-team-id") === m.awayTeamId));
    await saveOnPage(s, m);
    assert.equal(field(s, "phase1-home-team", m.id).disabled, true);
    assert.equal(field(s, "phase1-home", m.id).disabled, true);
    completePhase1(s); s.A.startKnockout();
    const first = s.state().knockout.rounds[0].matches[0];
    assert.ok(field(s, "ko-home-team", first.id));
    await field(s, "ko-home-team", first.id).focus();
    assert.ok(field(s, "ko-home-team", first.id).closest(".team-picker").querySelectorAll('[role="option"]')
        .every((option) => option.getAttribute("data-team-id")));
});
test("operator-page: qualifier select offers powers of two and flags stale values", async () => {
    const s = createSandbox({ page: "admin" });
    setup(s, 8, 2, { qualifiedCount: 8 });
    const selector = s.el("cfg-qualified");
    const message = s.el("qualified-count-message");
    assert.deepEqual(selector.querySelectorAll("option").map((option) => option.value), ["2", "4", "8"]);
    assert.equal(selector.value, "8");
    assert.equal(message.hidden, true);
    assert.equal(selector.getAttribute("aria-describedby"), null);

    s.A.removeTeam(s.state().teams[0].id);
    assert.equal(s.state().config.qualifiedCount, 8);
    assert.equal(selector.value, "8");
    assert.equal(selector.querySelectorAll("option")[0].disabled, true);
    assert.equal(message.hidden, false);
    assert.match(message.textContent, /invalid for 7 teams/);
    assert.equal(selector.getAttribute("aria-describedby"), message.id);
    assert.equal(s.el("btn-generate-phase1").disabled, true);
    selector.value = "4";
    await s.el("form-config").dispatch("submit");
    assert.equal(s.state().config.qualifiedCount, 4);
    assert.equal(message.hidden, true);
    assert.equal(selector.getAttribute("aria-describedby"), null);
    assert.equal(s.el("btn-generate-phase1").disabled, false);

    setup(s, 10, 2, { qualifiedCount: 10 });
    assert.equal(s.el("cfg-qualified").value, "10");
    assert.match(message.textContent, /Select a power of two/);
    assert.equal(s.el("btn-generate-phase1").disabled, true);
    await s.el("form-config").dispatch("submit");
    assert.match(s.alerts.at(-1), /power of two/);
});
test("operator-page: operator/summary/print standings headers, qualified cells and GA decimals", async () => {
    const s = createSandbox({ page: "admin" }); handFixture(s); s.S.update(() => {});
    const table = s.el("phase1-standings");
    assert.deepEqual(table.querySelectorAll("th").map((el) => el.textContent), HEADERS);
    assert.equal(table.querySelectorAll(".standings-qualified").length, 8);
    assert.match(table.innerHTML, />2\.50<\/td>/);
    s.el("export-print-content").value = "standings";
    await s.el("btn-export-print-generate").click();
    assert.deepEqual(s.el("print-root").querySelectorAll("th").map((el) => el.textContent), HEADERS);
    assert.match(s.el("print-root").innerHTML, />2\.50<\/td>/);
    const summary = createSandbox({ page: "summary", initial: { [STATE_KEY]: s.S.exportState() } });
    assert.deepEqual(summary.el("summary-standings").querySelectorAll("th").map((el) => el.textContent), HEADERS);
    assert.equal(summary.el("summary-standings").querySelectorAll(".standings-qualified").length, 8);
    assert.match(summary.el("summary-standings").innerHTML, />2\.50<\/td>/);
});
test("operator-page: A5 print saved scores and blank pending scores, print once", async () => {
    const s = createSandbox({ page: "admin" }); setup(s); s.A.generatePhase1();
    const m = s.state().phase1.matches[0]; s.A.applyPhase1Score(m.id, undefined, undefined, 7, 2);
    const pending = s.state().phase1.matches[1];
    field(s, "phase1-home", pending.id).value = "99";
    s.el("export-print-content").value = "phase"; s.el("export-print-paper").value = "A5";
    await s.el("btn-export-print").click(); assert.equal(s.el("export-print-panel").hidden, false);
    await s.el("btn-export-print").click(); assert.equal(s.el("export-print-panel").hidden, true);
    await s.el("btn-export-print-generate").click();
    assert.equal(s.prints, 1);
    assert.match(s.el("print-root").innerHTML, /7 - 2/);
    assert.match(s.el("print-root").innerHTML, /print-blank-score/);
    assert.doesNotMatch(s.el("print-root").innerHTML, /99/);
    assert.equal(s.el("print-page-size-style").textContent, "@page { size: 148mm 210mm; margin: 10mm; }");
    completePhase1(s); s.A.startKnockout();
    await s.el("btn-export-print-generate").click();
    assert.match(s.el("print-root").innerHTML, /Knockout Bracket/);
    assert.match(s.el("print-root").innerHTML, /print-blank-line/);
    s.A.resetAll();
    await s.el("btn-export-print-generate").click();
    assert.match(s.el("print-root").innerHTML, /No teams registered yet/);
});
test("operator-page: ticking clocks retain round+match pauses, stopped/final freeze and overtime", () => {
    const s = createSandbox({ page: "admin", now: 1000 });
    setup(s); s.A.generatePhase1();
    const m = s.state().phase1.matches[0];
    s.A.startPhase1RoundTimer(0);
    s.setNow(11000); s.A.pausePhase1RoundTimer(0);
    s.setNow(31000); s.A.resumePhase1RoundTimer(0);
    s.setNow(41000); s.A.pauseMatchTimer(m.id);
    s.setNow(46000); s.A.resumeMatchTimer(m.id);
    s.setNow(61000); s.runTimers(1000);
    assert.equal(field(s, "match-clock", m.id), null); // Clocks have timing attrs, not match IDs.
    let clocks = s.document.querySelectorAll('[data-role="match-clock"]');
    assert.equal(clocks[0].textContent, "09:25"); assert.equal(clocks[1].textContent, "09:20");
    s.setNow(650000); s.runTimers(1000);
    assert.equal(clocks[0].textContent, "+00:24"); assert.equal(clocks[0].classList.contains("overtime"), true);
    s.A.pauseMatchTimer(m.id); s.advance(130000); s.runTimers(1000);
    assert.equal(s.document.querySelector('[data-role="match-break"]').textContent, "Break: 00:50");
    s.A.resumeMatchTimer(m.id);
    s.A.pausePhase1RoundTimer(0); s.advance(10000); s.runTimers(1000);
    const frozen = s.document.querySelector('[data-role="match-clock"]').textContent;
    s.advance(10000); s.runTimers(1000);
    assert.equal(s.document.querySelector('[data-role="match-clock"]').textContent, frozen);
    s.A.resumePhase1RoundTimer(0); s.A.stopPhase1RoundTimer(0);
    const stopped = s.document.querySelector('[data-role="match-clock"]').textContent;
    s.advance(10000); s.runTimers(1000);
    assert.equal(s.document.querySelector('[data-role="match-clock"]').textContent, stopped);
    s.A.applyPhase1Score(m.id, undefined, undefined, 2, 0);
    const final = s.document.querySelector('[data-final-elapsed-ms]');
    assert.equal(final.textContent, s.T.formatDuration(m.finalElapsedMs));
    s.advance(10000); s.runTimers(1000);
    assert.equal(final.textContent, s.T.formatDuration(m.finalElapsedMs));
    assert.match(s.el("phase1-matches").innerHTML, /Round timer stopped/);
});
test("operator-page: confirmation cancel/apply for back/reset, separate preferences survive reset", async () => {
    const s = knockoutFixture({ page: "admin" });
    const before = s.S.exportState();
    s.confirmResult = false;
    for (const id of ["btn-back-to-phase1", "btn-reset-phases", "btn-reset-state"]) await s.el(id).click();
    assert.equal(s.S.exportState(), before);
    s.confirmResult = true;
    await s.el("btn-back-to-phase1").click();
    assert.equal(s.state().knockout.generated, false); assert.equal(s.state().phase1.generated, true);
    await s.el("btn-reset-phases").click();
    assert.equal(s.state().phase1.generated, false); assert.equal(s.state().teams.length, 4);
    await s.el("btn-toggle-summary-standings").click(); await s.el("btn-toggle-summary-scroll").click();
    await s.el("btn-expand-all").click();
    const prefs = s.storage.getItem(SUMMARY_KEY), ui = s.storage.getItem(OPERATOR_KEY);
    assert.deepEqual(JSON.parse(prefs), { standingsHidden: true, autoScrollActive: true });
    assert.equal(s.el("btn-toggle-summary-standings").textContent, "Standings: OFF");
    assert.equal(s.el("btn-toggle-summary-scroll").textContent, "Auto-scroll: ON");
    assert.equal(Object.hasOwn(s.state(), "standingsHidden"), false);
    await s.el("btn-reset-state").click();
    assert.equal(s.state().teams.length, 0);
    assert.equal(s.storage.getItem(SUMMARY_KEY), prefs); assert.equal(s.storage.getItem(OPERATOR_KEY), ui);
    await s.el("btn-toggle-summary-standings").click(); await s.el("btn-toggle-summary-scroll").click();
    assert.deepEqual(JSON.parse(s.storage.getItem(SUMMARY_KEY)), { standingsHidden: false, autoScrollActive: false });
});
test("operator-page: invalid/valid import, empty chooser and export event", async () => {
    const s = createSandbox({ page: "admin", initial: { [SUMMARY_KEY]: "{", [OPERATOR_KEY]: "{" } });
    await s.el("btn-import-state").click();
    assert.equal(s.document.clicks.at(-1), s.el("import-state-input"));
    const input = s.el("import-state-input");
    await input.dispatch("change", { target: { files: [] } });
    const before = s.S.exportState();
    await input.dispatch("change", { target: { files: [{ text: async () => "{" }] } });
    assert.equal(s.S.exportState(), before); assert.equal(s.alerts.length, 1);
    const fixture = createSandbox(); handFixture(fixture);
    await input.dispatch("change", { target: { files: [{ text: async () => fixture.S.exportState() }] } });
    assert.equal(s.state().teams.length, 4); assert.equal(input.value, "");
    assert.equal(s.state().audit[0].message, "Imported tournament state");
    await s.el("btn-export-state").click();
    assert.equal(s.blobs[0].parts[0], s.S.exportState());
    assert.deepEqual(plain(s.state().teams), plain(fixture.state().teams));
});
